/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnaliseSolicitacaoRouteImport } from './routes/analise-solicitacao'
import { Route as ParcelamentoRouteImport } from './routes/parcelamento'
import { Route as ResumoSolicitacaoRouteImport } from './routes/resumo-solicitacao'
import { Route as SimulacaoRouteImport } from './routes/simulacao'
import { Route as ApiPublicPinpayWebhookRouteImport } from './routes/api/public/pinpay-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseSolicitacaoRoute = AnaliseSolicitacaoRouteImport.update({
  id: '/analise-solicitacao',
  path: '/analise-solicitacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcelamentoRoute = ParcelamentoRouteImport.update({
  id: '/parcelamento',
  path: '/parcelamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumoSolicitacaoRoute = ResumoSolicitacaoRouteImport.update({
  id: '/resumo-solicitacao',
  path: '/resumo-solicitacao',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacaoRoute = SimulacaoRouteImport.update({
  id: '/simulacao',
  path: '/simulacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPinpayWebhookRoute = ApiPublicPinpayWebhookRouteImport.update({
  id: '/api/public/pinpay-webhook',
  path: '/api/public/pinpay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analise-solicitacao': typeof AnaliseSolicitacaoRoute
  '/parcelamento': typeof ParcelamentoRoute
  '/resumo-solicitacao': typeof ResumoSolicitacaoRoute
  '/simulacao': typeof SimulacaoRoute
  '/api/public/pinpay-webhook': typeof ApiPublicPinpayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analise-solicitacao': typeof AnaliseSolicitacaoRoute
  '/parcelamento': typeof ParcelamentoRoute
  '/resumo-solicitacao': typeof ResumoSolicitacaoRoute
  '/simulacao': typeof SimulacaoRoute
  '/api/public/pinpay-webhook': typeof ApiPublicPinpayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analise-solicitacao': typeof AnaliseSolicitacaoRoute
  '/parcelamento': typeof ParcelamentoRoute
  '/resumo-solicitacao': typeof ResumoSolicitacaoRoute
  '/simulacao': typeof SimulacaoRoute
  '/api/public/pinpay-webhook': typeof ApiPublicPinpayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analise-solicitacao'
    | '/parcelamento'
    | '/resumo-solicitacao'
    | '/simulacao'
    | '/api/public/pinpay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analise-solicitacao'
    | '/parcelamento'
    | '/resumo-solicitacao'
    | '/simulacao'
    | '/api/public/pinpay-webhook'
  id:
    | '__root__'
    | '/'
    | '/analise-solicitacao'
    | '/parcelamento'
    | '/resumo-solicitacao'
    | '/simulacao'
    | '/api/public/pinpay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnaliseSolicitacaoRoute: typeof AnaliseSolicitacaoRoute
  ParcelamentoRoute: typeof ParcelamentoRoute
  ResumoSolicitacaoRoute: typeof ResumoSolicitacaoRoute
  SimulacaoRoute: typeof SimulacaoRoute
  ApiPublicPinpayWebhookRoute: typeof ApiPublicPinpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise-solicitacao': {
      id: '/analise-solicitacao'
      path: '/analise-solicitacao'
      fullPath: '/analise-solicitacao'
      preLoaderRoute: typeof AnaliseSolicitacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcelamento': {
      id: '/parcelamento'
      path: '/parcelamento'
      fullPath: '/parcelamento'
      preLoaderRoute: typeof ParcelamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumo-solicitacao': {
      id: '/resumo-solicitacao'
      path: '/resumo-solicitacao'
      fullPath: '/resumo-solicitacao'
      preLoaderRoute: typeof ResumoSolicitacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacao': {
      id: '/simulacao'
      path: '/simulacao'
      fullPath: '/simulacao'
      preLoaderRoute: typeof SimulacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pinpay-webhook': {
      id: '/api/public/pinpay-webhook'
      path: '/api/public/pinpay-webhook'
      fullPath: '/api/public/pinpay-webhook'
      preLoaderRoute: typeof ApiPublicPinpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnaliseSolicitacaoRoute: AnaliseSolicitacaoRoute,
  ParcelamentoRoute: ParcelamentoRoute,
  ResumoSolicitacaoRoute: ResumoSolicitacaoRoute,
  SimulacaoRoute: SimulacaoRoute,
  ApiPublicPinpayWebhookRoute: ApiPublicPinpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
