/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParcelamentoRouteImport } from './routes/parcelamento'
import { Route as SimulacaoRouteImport } from './routes/simulacao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcelamentoRoute = ParcelamentoRouteImport.update({
  id: '/parcelamento',
  path: '/parcelamento',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacaoRoute = SimulacaoRouteImport.update({
  id: '/simulacao',
  path: '/simulacao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/parcelamento': typeof ParcelamentoRoute
  '/simulacao': typeof SimulacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/parcelamento': typeof ParcelamentoRoute
  '/simulacao': typeof SimulacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/parcelamento': typeof ParcelamentoRoute
  '/simulacao': typeof SimulacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/parcelamento' | '/simulacao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/parcelamento' | '/simulacao'
  id: '__root__' | '/' | '/parcelamento' | '/simulacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParcelamentoRoute: typeof ParcelamentoRoute
  SimulacaoRoute: typeof SimulacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcelamento': {
      id: '/parcelamento'
      path: '/parcelamento'
      fullPath: '/parcelamento'
      preLoaderRoute: typeof ParcelamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacao': {
      id: '/simulacao'
      path: '/simulacao'
      fullPath: '/simulacao'
      preLoaderRoute: typeof SimulacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParcelamentoRoute: ParcelamentoRoute,
  SimulacaoRoute: SimulacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
